name = "wayfind"
main = "src/index.ts"
compatibility_date = "2023-10-15"

[[vectorize]]
binding = "COURSES_INDEX"
index_name = "wayfind-courses"

[[vectorize]]
binding = "PROGRAMS_INDEX"
index_name = "wayfind-programs"
