export const schools = [
	{ id: 179, name: "Applewood Heights Secondary School" },
	{ id: 180, name: "Bramalea Secondary School" },
	{ id: 181, name: "Brampton Centennial Secondary School" },
	{ id: 182, name: "Cawthra Park Secondary School" },
	{ id: 183, name: "Central Peel Secondary School" },
	{ id: 184, name: "Chinguacousy Secondary School" },
	{ id: 185, name: "Clarkson Secondary School" },
	{ id: 186, name: "Erindale Secondary School" },
	{ id: 187, name: "Fletchers Meadow Secondary School" },
	{ id: 188, name: "Glenforest Secondary School" },
	{ id: 189, name: "Gordon Graydon Memorial Secondary School" },
	{ id: 190, name: "Harold M. Brathwaite Secondary School" },
	{ id: 191, name: "Heart Lake Secondary School" },
	{ id: 192, name: "John Fraser Secondary School" },
	{ id: 193, name: "Lincoln M. Alexander Secondary School" },
	{ id: 194, name: "Lorne Park Secondary School" },
	{ id: 195, name: "Mayfield Secondary School" },
	{ id: 196, name: "Meadowvale Secondary School" },
	{ id: 197, name: "Mississauga Secondary School" },
	{ id: 198, name: "North Park Secondary School" },
	{ id: 199, name: "Judith Nyman Secondary School" },
	{ id: 200, name: "Peel Alternative School North" },
	{ id: 202, name: "Sandalwood Heights Secondary School" },
	{ id: 203, name: "Port Credit Secondary School" },
	{ id: 204, name: "Rick Hansen Secondary School" },
	{ id: 205, name: "Stephen Lewis Secondary School" },
	{ id: 206, name: "Streetsville Secondary School" },
	{ id: 207, name: "T.L. Kennedy Secondary School" },
	{ id: 208, name: "Humberview Secondary School" },
	{ id: 209, name: "The Woodlands Secondary School" },
	{ id: 210, name: "Turner Fenton Secondary School" },
	{ id: 211, name: "West Credit Secondary School" },
	{ id: 509, name: "Peel Alternative School Central" },
	{ id: 554, name: "Louise Arbour Secondary School" },
	{ id: 607, name: "David Suzuki Secondary School" },
	{ id: 908, name: "Castlebrooke Secondary School" },
];
